extern const GeoLayout ramiel_charge_geo[];
extern Lights1 ramiel_charge_f3d_material_010_lights;
extern Lights1 ramiel_charge_f3d_material_011_lights;
extern u8 ramiel_charge_shoonen2_ia8[];
extern u8 ramiel_charge_spark_ci4[];
extern u8 ramiel_charge_spark_ci4_pal_rgba16[];
extern Vtx ramiel_charge_Circle_002_mesh_layer_4_vtx_cull[8];
extern Vtx ramiel_charge_Circle_002_mesh_layer_4_vtx_0[68];
extern Gfx ramiel_charge_Circle_002_mesh_layer_4_tri_0[];
extern Vtx ramiel_charge_Circle_002_mesh_layer_4_vtx_1[86];
extern Gfx ramiel_charge_Circle_002_mesh_layer_4_tri_1[];
extern Gfx mat_ramiel_charge_f3d_material_010[];
extern Gfx mat_revert_ramiel_charge_f3d_material_010[];
extern Gfx mat_ramiel_charge_f3d_material_011[];
extern Gfx mat_revert_ramiel_charge_f3d_material_011[];
extern Gfx ramiel_charge_Circle_002_mesh_layer_4[];
extern Gfx ramiel_charge_material_revert_render_settings[];
