extern const GeoLayout ramiel_shard_geo[];
extern u8 ramiel_shard_ramieltop_ci8[];
extern u8 ramiel_shard_ramieltop_ci8_pal_rgba16[];
extern Vtx ramiel_shard_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ramiel_shard_Cube_mesh_layer_1_vtx_0[12];
extern Gfx ramiel_shard_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_ramiel_shard_f3d_material_004[];
extern Gfx mat_revert_ramiel_shard_f3d_material_004[];
extern Gfx ramiel_shard_Cube_mesh_layer_1[];
extern Gfx ramiel_shard_material_revert_render_settings[];
