#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/sa/texture.inc.c"
#include "levels/sa/areas/1/1/model.inc.c"
#include "levels/sa/areas/1/2/model.inc.c"
#include "levels/sa/areas/1/collision.inc.c"
#include "levels/sa/areas/1/macro.inc.c"

#include "levels/sa/leveldata.inc.c"

#include "levels/sa/eva64/model.inc.c"
#include "levels/sa/intro_mario/model.inc.c"
#include "levels/sa/intro_mario/anims/data.inc.c"
#include "levels/sa/intro_mario/anims/table.inc.c"
#include "levels/sa/daisuka_sil/model.inc.c"
#include "levels/sa/daisuka_sil/anims/data.inc.c"
#include "levels/sa/daisuka_sil/anims/table.inc.c"
#include "levels/sa/reisalina_sil/model.inc.c"
#include "levels/sa/reisalina_sil/anims/data.inc.c"
#include "levels/sa/reisalina_sil/anims/table.inc.c"
#include "levels/sa/peasato_sil/model.inc.c"
#include "levels/sa/peasato_sil/anims/data.inc.c"
#include "levels/sa/peasato_sil/anims/table.inc.c"
#include "levels/sa/reisalina_intro/anims/data.inc.c"
#include "levels/sa/reisalina_intro/anims/table.inc.c"
#include "levels/sa/evi_intro/model.inc.c"
#include "levels/sa/evi_intro/anims/data.inc.c"
#include "levels/sa/evi_intro/anims/table.inc.c"