extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern Lights1 bob_dl_f3d_material_015_lights;
extern Lights1 bob_dl_f3d_material_017_lights;
extern Lights1 bob_dl_f3d_material_016_lights;
extern Lights1 bob_dl_f3d_material_022_lights;
extern Lights1 bob_dl_f3d_material_018_lights;
extern Lights1 bob_dl_f3d_material_019_lights;
extern u8 bob_dl_RMGP01_9176ad0a_14_ci8[];
extern u8 bob_dl_RMGP01_9176ad0a_14_ci8_pal_rgba16[];
extern u8 bob_dl_B5AD4D6_c_ci4[];
extern u8 bob_dl_B5AD4D6_c_ci4_pal_rgba16[];
extern u8 bob_dl__1F37C5E_c_ci4[];
extern u8 bob_dl__1F37C5E_c_ci4_pal_rgba16[];
extern u8 bob_dl__420C71EA_c_ci4[];
extern u8 bob_dl__420C71EA_c_ci4_pal_rgba16[];
extern u8 bob_dl_RMGP01_b03ac7f9_14_ci4[];
extern u8 bob_dl_RMGP01_b03ac7f9_14_ci4_pal_rgba16[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[6];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_1[12];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_2[8];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_3[20];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[28];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[175];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[21];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx mat_revert_bob_dl_f3d_material_001[];
extern Gfx mat_bob_dl_f3d_material_015[];
extern Gfx mat_revert_bob_dl_f3d_material_015[];
extern Gfx mat_bob_dl_f3d_material_017[];
extern Gfx mat_revert_bob_dl_f3d_material_017[];
extern Gfx mat_bob_dl_f3d_material_016[];
extern Gfx mat_bob_dl_f3d_material_022[];
extern Gfx mat_revert_bob_dl_f3d_material_022[];
extern Gfx mat_bob_dl_f3d_material_018[];
extern Gfx mat_revert_bob_dl_f3d_material_018[];
extern Gfx mat_bob_dl_f3d_material_019[];
extern Gfx mat_revert_bob_dl_f3d_material_019[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
