extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern Lights1 bob_dl_f3d_material_022_lights;
extern u8 bob_dl__420C71EA_c_ci4[];
extern u8 bob_dl__420C71EA_c_ci4_pal_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_5_vtx_0[28];
extern Gfx bob_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3d_material_022[];
extern Gfx mat_revert_bob_dl_f3d_material_022[];
extern Gfx bob_dl_Plane_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
