extern const GeoLayout blackmoon_geo[];
extern Lights1 blackmoon_f3d_material_003_lights;
extern Lights1 blackmoon_f3d_material_004_lights;
extern u8 blackmoon_tdsky_ci8[];
extern u8 blackmoon_tdsky_ci8_pal_rgba16[];
extern u8 blackmoon_coins_ci4[];
extern u8 blackmoon_coins_ci4_pal_rgba16[];
extern Vtx blackmoon_Sphere_mesh_layer_1_vtx_0[127];
extern Gfx blackmoon_Sphere_mesh_layer_1_tri_0[];
extern Vtx blackmoon_Sphere_mesh_layer_4_vtx_0[254];
extern Gfx blackmoon_Sphere_mesh_layer_4_tri_0[];
extern Gfx mat_blackmoon_f3d_material_003[];
extern Gfx mat_revert_blackmoon_f3d_material_003[];
extern Gfx mat_blackmoon_f3d_material_004[];
extern Gfx mat_revert_blackmoon_f3d_material_004[];
extern Gfx blackmoon_Sphere_mesh_layer_1[];
extern Gfx blackmoon_Sphere_mesh_layer_4[];
extern Gfx blackmoon_material_revert_render_settings[];
