extern const GeoLayout cross_geo[];
extern Lights1 cross_f3d_material_lights;
extern Lights1 cross_f3d_material_002_lights;
extern u8 cross_shoonen_ci4[];
extern u8 cross_shoonen_ci4_pal_rgba16[];
extern Vtx cross_Plane_mesh_layer_1_vtx_0[14];
extern Gfx cross_Plane_mesh_layer_1_tri_0[];
extern Vtx cross_Plane_mesh_layer_5_vtx_0[46];
extern Gfx cross_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_cross_f3d_material[];
extern Gfx mat_cross_f3d_material_002[];
extern Gfx mat_revert_cross_f3d_material_002[];
extern Gfx cross_Plane_mesh_layer_1[];
extern Gfx cross_Plane_mesh_layer_5[];
extern Gfx cross_material_revert_render_settings[];
